# Generated by Django 5.1.4 on 2024-12-22 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_server', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('flag_url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='adminaction',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='adminaction',
            name='action_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.permission'),
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo_url', models.CharField(max_length=255)),
                ('country_of_origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_server.country')),
            ],
        ),
        migrations.CreateModel(
            name='LeagueSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_server.league')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_date', models.DateField()),
                ('league_seaon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_server.leagueseason')),
            ],
        ),
        migrations.CreateModel(
            name='MatchAdminAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_action', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api_server.adminaction')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_server.match')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('nickname', models.CharField(max_length=255)),
                ('profile_photo_url', models.CharField(max_length=255)),
                ('country_of_origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_server.country')),
            ],
        ),
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurrence_minute', models.FloatField()),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_server.eventtype')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_server.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_server.player')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerAdminAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_action', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api_server.adminaction')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_server.player')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo_url', models.CharField(max_length=255)),
                ('country_of_origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_server.country')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerInMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes_player', models.FloatField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_server.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_server.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_server.team')),
            ],
        ),
        migrations.CreateModel(
            name='TeamAdminAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_action', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api_server.adminaction')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_server.team')),
            ],
        ),
    ]
