# Generated by Django 5.1.4 on 2024-12-22 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_server', '0002_country_eventtype_rename_user_id_adminaction_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='flag_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='league',
            name='logo_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='league',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='nickname',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='player',
            name='profile_photo_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('name', 'surname')},
        ),
    ]
