# Generated by Django 5.1.4 on 2025-01-01 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_server', '0003_alter_country_flag_url_alter_league_logo_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='league_seaon',
            new_name='league_season',
        ),
        migrations.AlterUniqueTogether(
            name='leagueseason',
            unique_together={('name', 'league')},
        ),
    ]
