# Generated by Django 5.1.4 on 2025-01-03 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_server', '0004_rename_league_seaon_match_league_season_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerinmatch',
            old_name='minutes_player',
            new_name='minutes_played',
        ),
    ]
