# Generated by Django 5.1.4 on 2025-01-07 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_server', '0005_rename_minutes_player_playerinmatch_minutes_played'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='flag_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
