# Generated by Django 5.1.4 on 2025-01-07 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_server', '0006_alter_country_flag_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
