# Generated by Django 5.1.4 on 2025-01-07 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_server', '0007_alter_country_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='logo_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
