# Generated by Django 5.1.4 on 2025-01-07 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_server', '0008_alter_league_logo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='logo_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
