# Generated by Django 5.1.4 on 2025-01-08 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_server', '0011_alter_player_profile_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchevent',
            name='occurrence_minute',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='playerinmatch',
            name='minutes_played',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
