import datetime


EXPECTED_MATCHES: tuple[dict] = (
    {"id": 7, "game_date": datetime.date(1958,6,24), "league_season_id": 5},
    {"id": 6, "game_date": datetime.date(1958,6,29), "league_season_id": 5},
    {"id": 4, "game_date": datetime.date(1990,6,24), "league_season_id": 4},
)
EXPECTED_MATCHES_FILTERED_BY_DATE: tuple[dict] = (
    {"id": 6, "game_date": datetime.date(1958,6,29), "league_season_id": 5},
    {"id": 4, "game_date": datetime.date(1990,6,24), "league_season_id": 4},
)
EXPECTED_TEAM_REPRESENTANTS: tuple[dict] = (
{"id": 128, "name": "Acácio Cordeiro", "surname": "Barreto", "nickname": None, "profile_photo_url": None, "country_of_origin_id": 15},
{"id": 112, "name": "Aldair Nascimento dos", "surname": "Santos", "nickname": None, "profile_photo_url": None, "country_of_origin_id": 15},
{"id": 118, "name": "Antônio de Oliveira", "surname": "Filho", "nickname": None, "profile_photo_url": None, "country_of_origin_id": 15},
{"id": 129, "name": "Bismarck Barreto", "surname": "Faria", "nickname": None, "profile_photo_url": None, "country_of_origin_id": 15},
{"id": 110, "name": "Carlos Caetano Bledorn", "surname": "Verri", "nickname": None, "profile_photo_url": None, "country_of_origin_id": 15},
{"id": 242, "name": "Carlos José", "surname": "Castilho", "nickname": None, "profile_photo_url": None, "country_of_origin_id": 15},
{"id": 111, "name": "Claudio Andre Mergen", "surname": "Taffarel", "nickname": None, "profile_photo_url": None, "country_of_origin_id": 15},
{"id": 115, "name": "Cláudio Ibrahim Vaz", "surname": "Leal", "nickname": None, "profile_photo_url": None, "country_of_origin_id": 15},
{"id": 243, "name": "Dejalma Pereira Dias dos", "surname": "Santos", "nickname": None, "profile_photo_url": None, "country_of_origin_id": 15},
{"id": 244, "name": "Dino", "surname": "Sani", "nickname": None, "profile_photo_url": None, "country_of_origin_id": 15},
{"id": 233, "name": "Édson Arantes do", "surname": "Nascimento", "nickname": None, "profile_photo_url": None, "country_of_origin_id": 15},
{"id": 241, "name": "Edvaldo Izidio", "surname": "Neto", "nickname": None, "profile_photo_url": None, "country_of_origin_id": 15},
{"id": 251, "name": "Edwaldo Alves de Santa", "surname": "Rosa", "nickname": None, "profile_photo_url": None, "country_of_origin_id": 15},
{"id": 234, "name": "Gylmar dos Santos", "surname": "Neves", "nickname": None, "profile_photo_url": None, "country_of_origin_id": 15},
{"id": 236, "name": "Hideraldo Luis", "surname": "Bellini", "nickname": None, "profile_photo_url": None, "country_of_origin_id": 15},
{"id": 116, "name": "Iomar do", "surname": "Nascimento", "nickname": None, "profile_photo_url": None, "country_of_origin_id": 15},
{"id": 249, "name": "Joel Antônio", "surname": "Martins", "nickname": None, "profile_photo_url": None, "country_of_origin_id": 15},
{"id": 114, "name": "Jorge José de Amorim", "surname": "Campos", "nickname": None, "profile_photo_url": None, "country_of_origin_id": 15},
{"id": 252, "name": "José", "surname": "Macia", "nickname": None, "profile_photo_url": None, "country_of_origin_id": 15},
{"id": 123, "name": "José Carlos da Costa", "surname": "Araújo", "nickname": None, "profile_photo_url": None, "country_of_origin_id": 15},
{"id": 127, "name": "José Carlos Nepomuceno", "surname": "Mozer", "nickname": None, "profile_photo_url": None, "country_of_origin_id": 15},
{"id": 239, "name": "José Ely de", "surname": "Miranda", "nickname": None, "profile_photo_url": None, "country_of_origin_id": 15},
{"id": 250, "name": "José João", "surname": "Altafini", "nickname": None, "profile_photo_url": None, "country_of_origin_id": 18},
{"id": 113, "name": "José Roberto Gama de", "surname": "Oliveira", "nickname": None, "profile_photo_url": None, "country_of_origin_id": 15},
{"id": 109, "name": "Luís Antônio Corrêa da", "surname": "Costa", "nickname": None, "profile_photo_url": None, "country_of_origin_id": 15},
{"id": 240, "name": "Manoel Francisco dos", "surname": "Santos", "nickname": None, "profile_photo_url": None, "country_of_origin_id": 15},
{"id": 253, "name": "Mário Jorge Lobo", "surname": "Zagallo", "nickname": None, "profile_photo_url": None, "country_of_origin_id": 15},
{"id": 122, "name": "Mauro Geraldo", "surname": "Galvao", "nickname": None, "profile_photo_url": None, "country_of_origin_id": 15},
{"id": 248, "name": "Mauro Ramos de", "surname": "Oliveira", "nickname": None, "profile_photo_url": None, "country_of_origin_id": 15},
{"id": 126, "name": "Milton Queiroz da", "surname": "Paixao", "nickname": None, "profile_photo_url": None, "country_of_origin_id": 15},
{"id": 247, "name": "Moacyr Claudino Pinto da", "surname": "Silva", "nickname": None, "profile_photo_url": None, "country_of_origin_id": 15},
{"id": 238, "name": "Nilton de", "surname": "Sordi", "nickname": None, "profile_photo_url": None, "country_of_origin_id": 15},
{"id": 235, "name": "Nilton dos Reis", "surname": "Santos", "nickname": None, "profile_photo_url": None, "country_of_origin_id": 15},
{"id": 237, "name": "Orlando Peçanha de", "surname": "Carvalho", "nickname": None, "profile_photo_url": None, "country_of_origin_id": 15},
{"id": 121, "name": "Paulo Silas do Prado", "surname": "Pereira", "nickname": None, "profile_photo_url": None, "country_of_origin_id": 15},
{"id": 130, "name": "Renato", "surname": "Portaluppi", "nickname": None, "profile_photo_url": None, "country_of_origin_id": 15},
{"id": 125, "name": "Ricardo Gomes", "surname": "Raymundo", "nickname": None, "profile_photo_url": None, "country_of_origin_id": 15},
{"id": 120, "name": "Ricardo Roberto Barreto da", "surname": "Rocha", "nickname": None, "profile_photo_url": None, "country_of_origin_id": 15},
{"id": 119, "name": "Ricardo Rogério de", "surname": "Brito", "nickname": None, "profile_photo_url": None, "country_of_origin_id": 15},
{"id": 117, "name": "Romário de Souza", "surname": "Faria", "nickname": None, "profile_photo_url": None, "country_of_origin_id": 15},
{"id": 245, "name": "Valdemar Rodrigues", "surname": "Martíns", "nickname": None, "profile_photo_url": None, "country_of_origin_id": 15},
{"id": 124, "name": "Valdo Cândido de Oliveira", "surname": "Filho", "nickname": None, "profile_photo_url": None, "country_of_origin_id": 15},
{"id": 254, "name": "Waldyr", "surname": "Pereira", "nickname": None, "profile_photo_url": None, "country_of_origin_id": 15},
{"id": 246, "name": "Zózimo Alves", "surname": "Calazães", "nickname": None, "profile_photo_url": None, "country_of_origin_id": 15},
)

EXPECTED_TEAM_REPRESENTANTS_FILTERED_BY_DATE: tuple[dict] = (
{"id": 128, "name": "Acácio Cordeiro", "surname": "Barreto", "nickname": None, "profile_photo_url": None, "country_of_origin_id": 15},
{"id": 112, "name": "Aldair Nascimento dos", "surname": "Santos", "nickname": None, "profile_photo_url": None, "country_of_origin_id": 15},
{"id": 118, "name": "Antônio de Oliveira", "surname": "Filho", "nickname": None, "profile_photo_url": None, "country_of_origin_id": 15},
{"id": 129, "name": "Bismarck Barreto", "surname": "Faria", "nickname": None, "profile_photo_url": None, "country_of_origin_id": 15},
{"id": 110, "name": "Carlos Caetano Bledorn", "surname": "Verri", "nickname": None, "profile_photo_url": None, "country_of_origin_id": 15},
{"id": 242, "name": "Carlos José", "surname": "Castilho", "nickname": None, "profile_photo_url": None, "country_of_origin_id": 15},
{"id": 111, "name": "Claudio Andre Mergen", "surname": "Taffarel", "nickname": None, "profile_photo_url": None, "country_of_origin_id": 15},
{"id": 115, "name": "Cláudio Ibrahim Vaz", "surname": "Leal", "nickname": None, "profile_photo_url": None, "country_of_origin_id": 15},
{"id": 243, "name": "Dejalma Pereira Dias dos", "surname": "Santos", "nickname": None, "profile_photo_url": None, "country_of_origin_id": 15},
{"id": 244, "name": "Dino", "surname": "Sani", "nickname": None, "profile_photo_url": None, "country_of_origin_id": 15},
{"id": 233, "name": "Édson Arantes do", "surname": "Nascimento", "nickname": None, "profile_photo_url": None, "country_of_origin_id": 15},
{"id": 241, "name": "Edvaldo Izidio", "surname": "Neto", "nickname": None, "profile_photo_url": None, "country_of_origin_id": 15},
{"id": 251, "name": "Edwaldo Alves de Santa", "surname": "Rosa", "nickname": None, "profile_photo_url": None, "country_of_origin_id": 15},
{"id": 234, "name": "Gylmar dos Santos", "surname": "Neves", "nickname": None, "profile_photo_url": None, "country_of_origin_id": 15},
{"id": 236, "name": "Hideraldo Luis", "surname": "Bellini", "nickname": None, "profile_photo_url": None, "country_of_origin_id": 15},
{"id": 116, "name": "Iomar do", "surname": "Nascimento", "nickname": None, "profile_photo_url": None, "country_of_origin_id": 15},
{"id": 249, "name": "Joel Antônio", "surname": "Martins", "nickname": None, "profile_photo_url": None, "country_of_origin_id": 15},
{"id": 114, "name": "Jorge José de Amorim", "surname": "Campos", "nickname": None, "profile_photo_url": None, "country_of_origin_id": 15},
{"id": 252, "name": "José", "surname": "Macia", "nickname": None, "profile_photo_url": None, "country_of_origin_id": 15},
{"id": 123, "name": "José Carlos da Costa", "surname": "Araújo", "nickname": None, "profile_photo_url": None, "country_of_origin_id": 15},
{"id": 127, "name": "José Carlos Nepomuceno", "surname": "Mozer", "nickname": None, "profile_photo_url": None, "country_of_origin_id": 15},
{"id": 239, "name": "José Ely de", "surname": "Miranda", "nickname": None, "profile_photo_url": None, "country_of_origin_id": 15},
{"id": 250, "name": "José João", "surname": "Altafini", "nickname": None, "profile_photo_url": None, "country_of_origin_id": 18},
{"id": 113, "name": "José Roberto Gama de", "surname": "Oliveira", "nickname": None, "profile_photo_url": None, "country_of_origin_id": 15},
{"id": 109, "name": "Luís Antônio Corrêa da", "surname": "Costa", "nickname": None, "profile_photo_url": None, "country_of_origin_id": 15},
{"id": 240, "name": "Manoel Francisco dos", "surname": "Santos", "nickname": None, "profile_photo_url": None, "country_of_origin_id": 15},
{"id": 253, "name": "Mário Jorge Lobo", "surname": "Zagallo", "nickname": None, "profile_photo_url": None, "country_of_origin_id": 15},
{"id": 122, "name": "Mauro Geraldo", "surname": "Galvao", "nickname": None, "profile_photo_url": None, "country_of_origin_id": 15},
{"id": 248, "name": "Mauro Ramos de", "surname": "Oliveira", "nickname": None, "profile_photo_url": None, "country_of_origin_id": 15},
{"id": 126, "name": "Milton Queiroz da", "surname": "Paixao", "nickname": None, "profile_photo_url": None, "country_of_origin_id": 15},
{"id": 247, "name": "Moacyr Claudino Pinto da", "surname": "Silva", "nickname": None, "profile_photo_url": None, "country_of_origin_id": 15},
{"id": 238, "name": "Nilton de", "surname": "Sordi", "nickname": None, "profile_photo_url": None, "country_of_origin_id": 15},
{"id": 235, "name": "Nilton dos Reis", "surname": "Santos", "nickname": None, "profile_photo_url": None, "country_of_origin_id": 15},
{"id": 237, "name": "Orlando Peçanha de", "surname": "Carvalho", "nickname": None, "profile_photo_url": None, "country_of_origin_id": 15},
{"id": 121, "name": "Paulo Silas do Prado", "surname": "Pereira", "nickname": None, "profile_photo_url": None, "country_of_origin_id": 15},
{"id": 130, "name": "Renato", "surname": "Portaluppi", "nickname": None, "profile_photo_url": None, "country_of_origin_id": 15},
{"id": 125, "name": "Ricardo Gomes", "surname": "Raymundo", "nickname": None, "profile_photo_url": None, "country_of_origin_id": 15},
{"id": 120, "name": "Ricardo Roberto Barreto da", "surname": "Rocha", "nickname": None, "profile_photo_url": None, "country_of_origin_id": 15},
{"id": 119, "name": "Ricardo Rogério de", "surname": "Brito", "nickname": None, "profile_photo_url": None, "country_of_origin_id": 15},
{"id": 117, "name": "Romário de Souza", "surname": "Faria", "nickname": None, "profile_photo_url": None, "country_of_origin_id": 15},
{"id": 245, "name": "Valdemar Rodrigues", "surname": "Martíns", "nickname": None, "profile_photo_url": None, "country_of_origin_id": 15},
{"id": 124, "name": "Valdo Cândido de Oliveira", "surname": "Filho", "nickname": None, "profile_photo_url": None, "country_of_origin_id": 15},
{"id": 254, "name": "Waldyr", "surname": "Pereira", "nickname": None, "profile_photo_url": None, "country_of_origin_id": 15},
{"id": 246, "name": "Zózimo Alves", "surname": "Calazães", "nickname": None, "profile_photo_url": None, "country_of_origin_id": 15},
)