from enum import Enum


OBJECTS_PER_PAGE: int = 25

# MATCH EVENTS
class MatchEvents(Enum):
    FAILED_PASS = "FAILED_PASS"
    SUCCESSFUL_PASS = "SUCCESSFUL_PASS"
    CORNER = "CORNER"
    YELLOW_CARD = "YELLOW_CARD"
    RED_CARD = "RED_CARD"
    GOAL = "GOAL"
    SHOT_ON_TARGET = "SHOT_ON_TARGET"
    SHOT_NOT_ON_TARGET = "SHOT_NOT_ON_TARGET"
    DEFENSE = "DEFENSE"
    WIN = "WIN"
    DEFEAT = "DEFEAT"
    DRAW = "DRAW"

# METRICS
class Metrics(Enum):
    SUM = 0
    AVERAGE = 1
    ODDS_FOR = 2
    ODDS_FOR_MORE_THAN = 3
    MINUTES_UNTIL = 4
    ODDS_IN_TIME_RANGE = 5

class MetricMatchScope(Enum):
    METRIC_FOR_ALL_MATCHES: int = -1
    METRIC_FOR_MATCHES_PLAYED_FOR_TEAM: int = -2

# FILTERS
class NumericFilteringCriteria(Enum):
    NUMERIC_EQUALS = "NUMERIC_EQUALS"
    NUMERIC_IN_CLOSED_RANGE = "NUMERIC_IN_CLOSED_RANGE"
    NUMERIC_NOT_IN_CLOSED_RANGE = "NUMERIC_NOT_IN_CLOSED_RANGE"

class TextualFilteringCriteria(Enum):
    TEXTUAL_FULL_TEXT_SEARCH = "TEXTUAL_FULL_TEXT_SEARCH"
    TEXTUAL_IN_SET = "TEXTUAL_IN_SET"
    TEXTUAL_NOT_IN_SET = "TEXTUAL_NOT_IN_SET"

USER_FILTER_ATTRIBUTES: list[str] = [
    "USERNAME"
]
PLAYER_FILTER_ATTRIBUTES: list[str] = [
    "NAME",
    "SURNAME",
    "NICKNAME",
    "COUNTRY_OF_ORIGIN_NAME",
    "TEAM_NAME",
    "LEAGUE_NAME"
]
TEAM_FILTER_ATTRIBUTES: list[str] = [
    "NAME",
    "PLAYER_NAME",
    "PLAYER_SURNAME",
    "LEAGUE_NAME",
    "COUNTRY_OF_ORIGIN_NAME"
]
MATCH_FILTER_ATTRIBUTES: list[str] = [
    "LEAGUE_NAME",
    "SEASON_NAME",
    "TEAM_NAME",
    "PLAYER_NAME",
    "PLAYER_SURNAME",
    "LEAGUE_COUNTRY_OF_ORIGIN_NAME",
    "DATE"
]

# SORTING
USER_SORT_ATTRIBUTES: list[str] = [
    "USERNAME"
]
PLAYER_SORT_ATTRIBUTES: list[str] = [
    "NAME",
    "SURNAME",
    "NICKNAME",
    "COUNTRY_OF_ORIGIN_NAME",
]
TEAM_SORT_ATTRIBUTES: list[str] = [
    "NAME",
    "COUNTRY_OF_ORIGIN_NAME"
]
MATCH_SORT_ATTRIBUTES: list[str] = [
    "LEAGUE_NAME",
    "SEASON_NAME",
    "LEAGUE_COUNTRY_OF_ORIGIN_NAME",
    "DATE"
]